### ISSUE TITLE
Peer Review 1 - Feedback on Strengths, Weaknesses, and Improvements to be made

### ISSUE THREAD

**Issue by brucejczhang** [sophiabrothers1/marathonfinishers#1]
**Summary:**
This project analyzes marathon completion times to uncover insights about factors influencing finishing performance. Utilizing a combination of exploratory data analysis, predictive modeling, and visualizations, the project aims to provide a detailed understanding of trends and key determinants for marathon completion rates. The work focuses on leveraging publicly available datasets and machine learning techniques for actionable insights.

**Strong positive points:**

1. Comprehensive data preprocessing: The data cleaning and preprocessing is well done. The scripts of data simulation and cleaning are done well. This is then well-represented in the measurement subsection of the data section, where each variable is clearly defined. 
2. Clear visualization: The graphs and figures used to represent the data comprehensively was very effective in communicating key insights and trends. 
3. Surveys, sampling, and observational data appendix: This section was done in a lot of detail with many key features highlighted for the existing sampling method. The proposed survey was also very well-done with a series of questions that can assess the full picture of the marathon runners' data. 

**Critical improvements needed:**

1. Incomplete README: The README document is not completed. The author must make sure to give an overview of the analysis and provide any other necessary information such as data and LLM usage. 
2. Missing LLM usage history: Remember to add the chat history of LLM usage in the “other” folder. 
4. Model explanation: The predictive models used are not fully justified, and the rationale for choosing specific algorithms or hyperparameter settings is missing. This diminishes confidence in the results.

**Suggestions for improvement:**

1. The figures may not need the figure titles given that this information is already provided in the figure caption. This will reduce redundancy in the information provided. 
2. You could expand on the introduction, adding more explanation to why the data that you looked at has real world implications. You may also want to consider citing more sources in the introduction. 
3. You could also incorporate additional visualizations, such as different ways in addition to boxplots, to further represent the model used and the prediction results. 
5. Include evaluation metrics like R2 values for model validation. This can help show the fit of the model used for the predictive purposes of the data. 
6. It was good that biases were addressed. A suggestion would be to explain a bit more about the demographic differences causing biases, just because there were many demographic factors that were focused on and they may have very different effects. 

**Evaluation:**

- R/Python cited (1/1 pt):  The programming language and tools used are cited. 
- Data cited (1/1 pt): The dataset is cited. 
- Class paper (1/1 pt): The title/description doesn’t show it is a class paper. 
- LLM documentation (0/1 pt): No chat history or mention of LLM usage. 
- Title (2/2 pts): Excellent. The title clearly reflects the content of the project.
- Author, date, and repo (2/2 pts):  The repository includes author and date information. The link to the github is provided. 
- Abstract (4/4 pts): Great and concise 4-sentence format highlighting the key points. 
- Introduction (3/4 pts): Key points covered. Could elaborate more on the background and reason of the analysis. 
- Estimand (1/1 pt): Present and concise.
- Data (8/10 pts): Variables represented in clear way. Figures support the understanding of the variables and their relationships. Can be improved by removing figure titles and making colors more consistent.  
- Measurement (4/4 pts): Clear definition of variables in a very readable way. 
- Model (7/10 pts): Predictive models are implemented very well with good reasoning. More statistical measures of the fit of the model can be included. 
- Results (9/10 pts): Well-represented results. Can be improved by improving formatting so the figures and explanations match better. 
- Discussion (10/10 pts): Thorough discussion of findings, advantages, and next steps of the model and current analysis. 
- Prose (6/6 pts): Excellent. Writing is clear and well-organized.
- Cross-references (1/1 pt):  Figures, tables, and sections are appropriately referenced.
- Captions (2/2 pts): Excellent. Captions are clear and relevant.
- Graphs/tables/etc. (3/4 pts):  Visualizations are informative. Can be improved by removing titles and improving color consistency. 
- Surveys, sampling, and observational data appendix (10/10 pts): This section was very well done. A lot of details was put into identifying the sampling methods’ advantages and disadvantages and designing a survey that would be useful for data collection in this scenario. 
- Referencing (4/4 pts): References were constructed correctly with no key citations or pieces of citations missing. 
- Commits (1/2 pts): Current commits have meaningful commit messages. More commits can be added as the paper is further polished. 
- Sketches (0/2 pts): Sketches are currently missing. 
- Simulation (4/4 pts): Data is well-simulated with meaningful comments in the script. 
- Tests (4/4 pts): Testing is well-done for both simulated and analysis data
- Parquet (1/1 pt): Simulated and analysis data files are both saved in parquet format. 
- Reproducible workflow (2/4 pts): Scripts are made easy to follow with comments. Having a README would largely include reproducibility. 
- Enhancements (4/4 pts): Shiny application done and is very thorough. 
- Miscellaneous (3/3 pts): The paper was of very high quality overall. 

**Estimated overall mark:**
98/112 = 87.5%
(Graded assuming LLM implementation would be updated before submission)
Grade without LLM statement: 0/112

**Other comments:**
This project is an excellent effort in understanding and predicting marathon finishing times. The information was interesting to read and the figures and results were interesting to see. There are very few things that are critically needed for the paper. Most suggestions are small things that can be fixed to improve the overall readability and flow of the paper. Great work overall!

**Comment by sophiabrothers1** [comment]
Thank you for the feedback! I added a readme, llm history, got rid of figure titles, expanded upon the model section, and elaborated more on the introduction to account for this feedback.
