### ISSUE TITLE
peer review 3 by qisheng yu

### ISSUE THREAD

**Issue by qishengyu** [sophiabrothers1/marathonfinishers#3]
**Summary:**
This article comprehensively and deeply analyzes the completion time of marathon races, aiming to accurately reveal various factors that affect completion results through the study of this key data. This article cleverly combines exploratory data analysis, predictive modeling, and visualization techniques. The goal is to gain a comprehensive and multi-level understanding of the development trends and crucial determinants of marathon completion rates. This significant work focuses on fully utilizing publicly available large-scale datasets.

**Strong positive points:**
Comprehensive data preprocessing: The data cleaning and preprocessing is well done. The scripts of data simulation and cleaning are done well. This is then well-represented in the measurement subsection of the data section, where each variable is clearly defined.
Clear visualization: The charts and graphs of data are highly effective in conveying key insights and trends.

**Critical improvements needed:**
Incomplete README: The README document is not completed. 
Missing LLM usage history: Remember to add the chat history of LLM usage in the “other” folder.

**Suggestions for improvement:**
The figures may not need the figure titles given that this information is already provided in the figure caption. This will reduce redundancy in the information provided.
You could expand on the introduction, adding more explanation to why the data that you looked at has real world implications. You may also want to consider citing more sources in the introduction.

**Evaluation:**
R/Python cited (1/1 pt): The programming language and tools used are cited.
Data cited (1/1 pt): The dataset is cited.
Class paper (1/1 pt): The title/description doesn’t show it is a class paper.
LLM documentation (0/1 pt): No chat history or mention of LLM usage.
Title (2/2 pts): Excellent. The title clearly reflects the content of the project.
Author, date, and repo (2/2 pts): The repository includes author and date information. The link to the github is provided.
Abstract (4/4 pts): Great and concise 4-sentence format highlighting the key points.
Introduction (3/4 pts): Key points covered. Could elaborate more on the background and reason of the analysis.
Estimand (1/1 pt): Present and concise.
Data (6/10 pts): Variables represented in clear way. 
Measurement (4/4 pts): Clear definition of variables in a very readable way.
Model (6/10 pts): Predictive models are implemented very well with good reasoning. 
Results (5/10 pts): Well-represented results. Can be improved by improving formatting so the figures and explanations match better.
Discussion (10/10 pts): Thorough discussion of findings, advantages, and next steps of the model and current analysis.
Prose (6/6 pts): Excellent. Writing is clear and well-organized.
Cross-references (1/1 pt): Figures, tables, and sections are appropriately referenced.
Captions (2/2 pts): Excellent. Captions are clear and relevant.
Graphs/tables/etc. (3/4 pts): Visualizations are informative.
Surveys, sampling, and observational data appendix (9/10 pts): This section well done
Referencing (4/4 pts): References were constructed correctly
Commits (1/2 pts): Current commits have meaningful commit messages. More commits can be added as the paper is further polished.
Sketches (0/2 pts):  missing.
Simulation (4/4 pts): Data is well-simulated with meaningful comments in the script.
Tests (4/4 pts): Testing is well-done for both simulated and analysis data
Parquet (0/1 pt): missing
Reproducible workflow (2/4 pts): Scripts are made easy to follow with comments. Having a README would largely include reproducibility.
Enhancements (2/4 pts): Shiny application done and is very thorough.
Miscellaneous (2/3 pts): The paper was of normal quality.

**Estimated overall mark:**
84/112

**Other comments:**
This essay is an excellent effort in understanding and predicting marathon finishing times.

**Comment by sophiabrothers1** [comment]
Thank you for the feedback! I added a readme as well as my llm history. I also got rid of the figure titles and expanded on the introduction.
